name: Continuous Integration

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Clean install dependencies, and build with Gatsby
      run: |
        npm ci
        npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Run linter and unit tests
      run: |
        npm run lint
        npm run test

