name: Continuous Deployment

on:
  push:
    branches: [ develop ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup GitHub user
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Clean install dependencies
      run: npm ci

    - name: Build and deploy to GitHub Pages with Gatsby
      run: npm run deploy
