name: Continuous Integration

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clean install dependencies
      run: npm ci

    - name: Build with Gatsby
      run: npm run build

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Run linter and unit tests
      run: |
        npm run lint
        npm run test
