name: Continuous Integration

on:
  pull_request:
    branches: [ develop ]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clean install dependencies
      run: npm ci

    - name: Build with Gatsby
      run: npm run build

    - name: Run linter and unit tests
      run: |
        npm run lint
        npm run test
